# Generated by Django 5.2.7 on 2025-10-04 19:16

import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Variable name (e.g., 'company_name', 'interview_location')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the variable', max_length=150)),
                ('default_value', models.CharField(blank=True, help_text='Default value if not provided', max_length=500)),
            ],
            options={
                'verbose_name': 'Custom Variable',
                'verbose_name_plural': 'Custom Variables',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name for internal use', max_length=200)),
                ('subject', models.CharField(help_text='Email subject line (supports placeholders)', max_length=300)),
                ('body', froala_editor.fields.FroalaField(help_text="Email body with rich text formatting.        Use {{name}}, {{email}}, {{position}}, {{interview_date}}, {{interview_time}}, or any custom variables you've created")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Position name (e.g., 'Software Engineer', 'Product Manager')", max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this position')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Template type name (e.g., '1st Interview', 'Job Offer')", max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Template Type',
                'verbose_name_plural': 'Template Types',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('position', models.ForeignKey(blank=True, help_text='Position/role applied for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=300)),
                ('body', froala_editor.fields.FroalaField()),
                ('interview_datetime', models.DateTimeField(blank=True, help_text='Interview date and time (optional)', null=True)),
                ('custom_variables', models.JSONField(blank=True, default=dict, help_text='Custom variable values used in this email')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('bcc_recipients', models.ManyToManyField(blank=True, help_text='BCC recipients (not visible to main recipient)', related_name='bcc_sent_emails', to='emails.recipient')),
                ('cc_recipients', models.ManyToManyField(blank=True, help_text='CC recipients (visible to all recipients)', related_name='cc_sent_emails', to='emails.recipient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='emails.recipient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailtemplate')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SentEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sent_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emails.sentemail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.ForeignKey(help_text='Category of this template', on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='emails.templatetype'),
        ),
    ]
