services:
  development:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # container_name: development
    environment:
      - DJANGO_DEVELOPMENT=True

